Fix build error: Remove non-existent German locale include
- Removed #include <dt-bindings/zmk/locale/keys_de.h> (file doesn't exist)
- Reverted to NON_US_BSLH keycode to fix compilation error
- The German locale support may not be available in this ZMK version

Build was failing with: dt-bindings/zmk/locale/keys_de.h: No such file or directory